"""
traceability.py — Traceability Record for V8.0 Data-First Engine.

Every test case generated by the V8.0 engine MUST have a TraceabilityRecord
linking it back to the specific data source that justifies its existence.
If a TC cannot be traced to a source, it should not exist.

Source types:
  - "Jira AC"          — extracted from Jira acceptance criteria text
  - "Chalk Scenario"   — extracted from Chalk API page scenario table
  - "Business Rule"    — extracted from Chalk Business Rules table (error codes)
  - "Subtask AC"       — extracted from subtask acceptance criteria
  - "NBOP UI"          — extracted from NBOP UI knowledge/crawl data
  - "Attachment"       — extracted from LLD/HLD/spec attachments
  - "Related Feature"  — extracted from same API in another PI's Chalk data
"""
from dataclasses import dataclass


# Allowed source_type values — any other value is invalid
ALLOWED_SOURCE_TYPES = frozenset([
    "Jira AC",
    "Chalk Scenario",
    "Business Rule",
    "Subtask AC",
    "NBOP UI",
    "Attachment",
    "Related Feature",
])


@dataclass
class TraceabilityRecord:
    """Links a test case to its originating data source.

    Fields:
        source_type:    One of ALLOWED_SOURCE_TYPES identifying the data source category.
        source_id:      Unique identifier within the source (e.g., "MDA-3941", "ERR06", "T008").
        extracted_text: The exact text from the source that justifies this test case.
        pi_label:       Program Increment label where the data was found (optional).
        confidence:     1.0 = direct extraction, 0.8 = inferred from context.
    """
    source_type: str
    source_id: str
    extracted_text: str
    pi_label: str = ''
    confidence: float = 1.0


def create_traceability(
    source_type: str,
    source_id: str,
    extracted_text: str,
    pi_label: str = '',
    confidence: float = 1.0,
) -> TraceabilityRecord:
    """Create a validated TraceabilityRecord.

    Validates:
      - source_type is non-empty and in ALLOWED_SOURCE_TYPES
      - source_id is non-empty
      - extracted_text is non-empty

    Raises:
        ValueError: If any validation fails.
    """
    # Strip whitespace for validation
    _source_type = source_type.strip() if source_type else ''
    _source_id = source_id.strip() if source_id else ''
    _extracted_text = extracted_text.strip() if extracted_text else ''

    if not _source_type:
        raise ValueError("source_type must be non-empty")
    if _source_type not in ALLOWED_SOURCE_TYPES:
        raise ValueError(
            "source_type '%s' is not allowed. Must be one of: %s"
            % (_source_type, ', '.join(sorted(ALLOWED_SOURCE_TYPES)))
        )
    if not _source_id:
        raise ValueError("source_id must be non-empty")
    if not _extracted_text:
        raise ValueError("extracted_text must be non-empty")

    return TraceabilityRecord(
        source_type=_source_type,
        source_id=_source_id,
        extracted_text=_extracted_text,
        pi_label=pi_label.strip() if pi_label else '',
        confidence=confidence,
    )
